### ISSUE TITLE
Development mode startup error

### ISSUE THREAD

**Issue by Dec-F** [SpongeNobody/Clashy#13]
```
Error: ENOENT: no such file or directory, chmod '/Users/dec-f/Project/Clashy/node_modules/electron/dist/Electron.app/Contents/Resources/clash-binaries/clash-darwin-amd64'
    at Object.chmodSync (fs.js:1079:3)
    at Object._spawnClash [as spawnClash] (/Users/dec-f/Project/Clashy/src/native-support/clash-binary.js:53:16)
    at /Users/dec-f/Project/Clashy/main.js:109:25
```

Follow the readme steps to start the electron and it appears that the path is wrong.

Are there any other steps required?

os: macos 10.15.2
node: v12.13.0

**Comment by Dec-F** [comment]
Need to add environment variables
![image](https://user-images.githubusercontent.com/20250430/71568868-740c1080-2b05-11ea-8080-dd4cea28bdd2.png)

Is this a bug, or is it intentional?🐶
