### ISSUE TITLE
kernel 5.16.9 版本0.2.5闪退

### ISSUE THREAD

**Issue by SHsdust** [SpongeNobody/Clashy#98]
我的系统是Arch，内核版本5.16.9，在5.16.8内核时一切正常，刚更新到5.16.9之后就出现了启动闪退的情况。

PPIMAGE env is not defined, current application is not an AppImage
20:34:16.000 › time="2022-02-15T20:34:15+08:00" level=info msg="Start initial compatible provider auto"
time="2022-02-15T20:34:16+08:00" level=info msg="Start initial compatible provider Proxy"
time="2022-02-15T20:34:16+08:00" level=info msg="Start initial compatible provider fallback-auto"

20:34:16.004 › time="2022-02-15T20:34:16+08:00" level=error msg="External controller listen error: listen tcp 127.0.0.1:2390: bind: address already in use"

(node:25251) UnhandledPromiseRejectionWarning: Error: socket hang up
    at connResetException (internal/errors.js:608:14)
    at Socket.socketOnEnd (_http_client.js:453:23)
    at Socket.emit (events.js:322:22)
    at endReadableNT (_stream_readable.js:1187:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:25251) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:25251) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
20:34:16.954 › time="2022-02-15T20:34:16+08:00" level=warning msg="[CacheFile] can't open cache file: timeout"

[25251:0215/203417.805832:FATAL:gpu_data_manager_impl_private.cc(442)] GPU process isn't usable. Goodbye.
[1]    25251 trace trap (core dumped)  clashy

**Comment by sommio** [comment]
建议 `mkinitcpio -p KernelName`看看是否报错 firmware 缺少，archlinux 在上个月为了精简拆分了 `linux-firmware`

**Comment by SpongeNobody** [comment]
Seems like port 2390 is already taken by other processes. Have you tried changing `Clashy`'s default port? I may consider changing default ports in next release but this is a breaking change.
